// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecSys.Models;

#nullable disable

namespace RecSys.Migrations
{
    [DbContext(typeof(RecSysContext))]
    partial class RecSysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecSys.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<string>("Abbreviations")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("abbreviations");

                    b.Property<string>("CourseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("courseCode");

                    b.Property<string>("CourseName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("courseName");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__2AA84FD12B199746");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("RecSys.Models.CourseLecturer", b =>
                {
                    b.Property<int>("SvId")
                        .HasColumnType("int")
                        .HasColumnName("svId");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("courseId");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.Property<int>("Sem")
                        .HasColumnType("int")
                        .HasColumnName("sem");

                    b.HasKey("SvId", "CourseId", "Year", "Sem")
                        .HasName("PK__CourseLe__733F8E5E9FB58C9E");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseLecturer", (string)null);
                });

            modelBuilder.Entity("RecSys.Models.Lecturer", b =>
                {
                    b.Property<int>("SvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SvId"), 1L, 1);

                    b.Property<int?>("Eligibility")
                        .HasColumnType("int")
                        .HasColumnName("eligibility");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SvExpertise")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("svExpertise");

                    b.Property<string>("SvName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("svName");

                    b.HasKey("SvId")
                        .HasName("PK__Lecturer__31A84D7B6411AC8F");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("RecSys.Models.PastStudentsChoice", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("studentId");

                    b.Property<string>("ProjectFocus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("project_focus");

                    b.Property<double?>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("rating");

                    b.Property<int?>("SvId")
                        .HasColumnType("int")
                        .HasColumnName("svId");

                    b.HasKey("StudentId")
                        .HasName("PK__past_stu__4D11D63C99A35C74");

                    b.ToTable("past_students_choices", (string)null);
                });

            modelBuilder.Entity("RecSys.Models.RecHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"), 1L, 1);

                    b.Property<Guid>("AnonymousId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreferredCourses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectFocus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("HistoryId")
                        .HasName("PK__RecHisto__4D7B4ABDCC5A894D");

                    b.ToTable("RecHistory", (string)null);
                });

            modelBuilder.Entity("RecSys.Models.RecRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"), 1L, 1);

                    b.Property<int>("HistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedLecturerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SubmittedRating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("RatingId")
                        .HasName("PK__RecRatin__FCCDF87CBED54A06");

                    b.HasIndex("HistoryId");

                    b.HasIndex("RecommendedLecturerId");

                    b.ToTable("RecRatings");
                });

            modelBuilder.Entity("RecSys.Models.CourseLecturer", b =>
                {
                    b.HasOne("RecSys.Models.Course", "Course")
                        .WithMany("CourseLecturers")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseLec__cours__70DDC3D8");

                    b.HasOne("RecSys.Models.Lecturer", "Sv")
                        .WithMany("CourseLecturers")
                        .HasForeignKey("SvId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseLect__svId__6FE99F9F");

                    b.Navigation("Course");

                    b.Navigation("Sv");
                });

            modelBuilder.Entity("RecSys.Models.RecRating", b =>
                {
                    b.HasOne("RecSys.Models.RecHistory", "History")
                        .WithMany("RecRatings")
                        .HasForeignKey("HistoryId")
                        .IsRequired()
                        .HasConstraintName("FK__RecRating__Histo__05D8E0BE");

                    b.HasOne("RecSys.Models.Lecturer", "RecommendedLecturer")
                        .WithMany()
                        .HasForeignKey("RecommendedLecturerId")
                        .HasConstraintName("FK_RecRating_Lecturer");

                    b.Navigation("History");

                    b.Navigation("RecommendedLecturer");
                });

            modelBuilder.Entity("RecSys.Models.Course", b =>
                {
                    b.Navigation("CourseLecturers");
                });

            modelBuilder.Entity("RecSys.Models.Lecturer", b =>
                {
                    b.Navigation("CourseLecturers");
                });

            modelBuilder.Entity("RecSys.Models.RecHistory", b =>
                {
                    b.Navigation("RecRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
